version = 3

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}}'
    foreground = '#26C6DA'
    type = 'os'
    style = 'plain'

    [blocks.segments.properties]
      macos = 'mac'

  [[blocks.segments]]
    template = ' {{ .UserName }}: '
    foreground = '#26C6DA'
    type = 'session'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'lightGreen'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'unique'

  [[blocks.segments]]
    template = '<#ffffff>on</> {{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ''
      fetch_stash_count = true

  [[blocks.segments]]
    template = '[ {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}] '
    foreground = '#906cff'
    type = 'python'
    style = 'powerline'

  [[blocks.segments]]
    template = '[ {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}] '
    foreground = '#7FD5EA'
    type = 'go'
    style = 'powerline'

  [[blocks.segments]]
    template = '[ {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}] '
    foreground = '#76b367'
    type = 'node'
    style = 'powerline'

  [[blocks.segments]]
    template = '[{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}] '
    foreground = '#f44336'
    type = 'ruby'
    style = 'powerline'

  [[blocks.segments]]
    template = '[ {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}] '
    foreground = '#ea2d2e'
    type = 'java'
    style = 'powerline'

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#4063D8'
    type = 'julia'
    style = 'powerline'

  [[blocks.segments]]
    template = '❯ '
    foreground = '#FFD54F'
    type = 'text'
    style = 'plain'
