# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  ...
}:
let
  inherit (lib) mkDefault mkEnableOption mkIf;
  cfg = config.wunkus.disks.dualBooty;
in
{
  options = {
    wunkus.disks.dualBooty.enable = mkEnableOption "dual boot disk config";
  };

  config = mkIf cfg.enable {
    fileSystems = {
      "/" = {
        device = "/dev/nixvg/nixos";
        fsType = "btrfs";
        options = [
          "subvol=@"
          "compress=zstd:3"
          "noatime"
        ];
      };

      "/home" = {
        device = "/dev/nixvg/nixos";
        fsType = "btrfs";
        neededForBoot = true;
        options = [
          "subvol=@home"
          "compress=zstd:3"
          "noatime"
        ];
      };

      "/nix" = {
        device = "/dev/nixvg/nixos";
        fsType = "btrfs";
        neededForBoot = true;
        options = [
          "subvol=@nix"
          "compress=zstd:3"
          "noatime"
        ];
      };

      "/persist" = {
        device = "/dev/nixvg/nixos";
        fsType = "btrfs";
        neededForBoot = true;
        options = [
          "subvol=@persist"
          "compress=zstd:3"
          "noatime"
        ];
      };

      "/home/.snapshots" = {
        device = "/dev/nixvg/nixos";
        fsType = "btrfs";
        depends = [ "/home" ];
        options = [
          "subvol=@home@.snapshots"
          "compress=zstd:3"
          "noatime"
        ];
      };

      "/boot" = {
        device = "/dev/disk/by-label/SYSTEM";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
          "noatime"
          "nosuid"
          "nodev"
          "noexec"
        ];
      };
    };

    swapDevices = [
      {
        device = "/dev/nixvg/swap";
        discardPolicy = "both";
      }
    ];
    zramSwap = {
      enable = mkDefault true;
      priority = mkDefault 100;
    };
    boot.initrd.luks.devices."nixcrypt" = {
      device = "/dev/disk/by-label/nixcrypt";
      allowDiscards = true;
    };
  };
}
