-- harpoon2.lua
local harpoon = require("harpoon")
harpoon:setup()
vim.keymap.set("n", "<leader>ha", function()
	harpoon:list():add()
end, { desc = "Add current file to harpoon" })
vim.keymap.set("n", "<leader>hd", function()
	harpoon:list():remove()
end, { desc = "Remove file from harpoon." })
vim.keymap.set("n", "<leader>hh", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = "Show harpoon." })

vim.keymap.set("n", "<leader>a", function()
	harpoon:list():select(1)
end)
vim.keymap.set("n", "<leader>s", function()
	harpoon:list():select(2)
end)
vim.keymap.set("n", "<leader>q", function()
	harpoon:list():select(3)
end)
vim.keymap.set("n", "<leader>w", function()
	harpoon:list():select(4)
end)
vim.keymap.set("n", "<leader>5", function()
	harpoon:list():select(5)
end)
vim.keymap.set("n", "<leader>6", function()
	harpoon:list():select(6)
end)
vim.keymap.set("n", "<leader>7", function()
	harpoon:list():select(7)
end)
vim.keymap.set("n", "<leader>8", function()
	harpoon:list():select(8)
end)
vim.keymap.set("n", "<leader>9", function()
	harpoon:list():select(9)
end)
vim.keymap.set("n", "<leader>0", function()
	harpoon:list():select(10)
end)
